"""
Bază de date cu cuvinte pentru joc pe nivele de dificultate
"""

WORDS = {
    "usor": [
        "CAT", "DOG", "SUN", "CAR", "RED", "BOY", "RUN", "EAT", "BIG", "HOT",
        "ICE", "TREE", "BOOK", "FISH", "BIRD", "LOVE", "BLUE", "FAST", "COLD", "WARM",
        "HAT", "BED", "CUP", "BAG", "TOY", "PEN", "EGG", "BOX", "KEY", "MAN"
    ],
    "mediu": [
        "PYTHON", "COMPUTER", "KEYBOARD", "MONITOR", "INTERNET", "WEBSITE", 
        "DATABASE", "FUNCTION", "VARIABLE", "OBJECT", "SCHOOL", "FRIEND", 
        "FAMILY", "HAPPY", "STRONG", "BRIGHT", "QUIET", "NATURE", "MOUNTAIN", "OCEAN",
        "GUITAR", "PLANET", "CASTLE", "DRAGON", "FOREST", "BRIDGE", "ROCKET", "GARDEN"
    ],
    "greu": [
        "JAVASCRIPT", "PROGRAMMING", "ALGORITHM", "FRAMEWORK", "DEVELOPMENT",
        "ARCHITECTURE", "OPTIMIZATION", "DEPLOYMENT", "CONFIGURATION", "AUTHENTICATION",
        "ENCRYPTION", "ABSTRACTION", "INHERITANCE", "POLYMORPHISM", "ENCAPSULATION",
        "ADVENTURE", "KNOWLEDGE", "CHALLENGE", "DISCOVERY", "UNIVERSE", "CREATIVE"
    ],
    "expert": [
        "CRYPTOCURRENCY", "MICROSERVICES", "CONTAINERIZATION", "ORCHESTRATION",
        "VIRTUALIZATION", "PARALLELIZATION", "SYNCHRONIZATION", "MULTITHREADING",
        "ASYNCHRONOUS", "RESPONSIBILITY", "ACCOUNTABILITY", "SUSTAINABILITY",
        "IMPLEMENTATION", "TRANSFORMATION", "REVOLUTIONARY", "EXTRAORDINARY",
        "CONSTITUTIONAL", "INTERDISCIPLINARY", "INTERNATIONALLY", "CHARACTERIZATION"
    ]
}
